//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberCrew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.MoneyIncome = new HashSet<MoneyIncome>();
        }
    
        public int ClientId { get; set; }
        public string Nickname { get; set; }
        public string HashedPassword { get; set; }
        public string Email { get; set; }
        public bool IsEmailConfirmed { get; set; }
        public System.DateTime RegisteredAt { get; set; }
        public decimal Balance { get; set; }
        public string EmailMessageCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyIncome> MoneyIncome { get; set; }
    }
}
