//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberCrew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ComputerId { get; set; }
        public int GPUId { get; set; }
        public int CPUId { get; set; }
        public short RAMGB { get; set; }
        public int StorageId { get; set; }
        public int Amount { get; set; }
        public string Description { get; set; }
    
        public virtual CPU CPU { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
