//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberCrew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyIncome
    {
        public int Id { get; set; }
        public System.DateTime IncomeDateTime { get; set; }
        public int IncomeSourceId { get; set; }
        public decimal MoneyAmount { get; set; }
        public int EmployeeId { get; set; }
        public int ClientId { get; set; }
    
        public virtual IncomeSource IncomeSource { get; set; }
    }
}
