//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberCrew.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public byte[] Icon { get; set; }
        public string PathToExe { get; set; }
        public string Description { get; set; }
    }
}
